;; gum is
;; useful
;; markup
;;
;; Reference:
;; https://github.com/toml-lang/toml/blob/main/toml.abnf
;; https://json5.dev/spec/grammar
;; https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form

document     = block-ws [ assignment *( element-sep assignment ) ] [ trailing-sep ]
comment-line = *ws comment nl

assignment   = path *ws "=" *ws value
path         = key *( *ws "." *ws key )

;; Keys = Values
;; NOTE: "bare" keys cannot be true, false, or null
key          = bare-key / quoted-string
bare-key     = (ALPHA / underscore) *( ALPHA / DIGIT / underscore )
value        = false / true / null / table / array / number / string
underscore   = %x5f ; _

;; Data Types
false        = %x66.61.6c.73.65 ; false
true         = %x74.72.75.65 ; true
null         = %x6e.75.6c.6c ; null

;; Collections
table        = "{" block-ws [ assignment *( element-sep assignment ) ] [ trailing-sep ] block-ws "}"
array        = "[" block-ws [ value      *( element-sep value      ) ] [ trailing-sep ] block-ws "]"

element-sep  = *ws [ comment ] ( "," / nl ) block-ws
trailing-sep = *ws [ comment ] [ "," ] block-ws

;; Strings
string           = multiline-string / quoted-string

quotation-mark   = %x22 ; "
triple-quote     = %x22.22.22 ; """
escape-seq       = escape ( %x22 / %x5C / %x2F / %x62 / %x66 / %x6E / %x72 / %x74 / %x75 4HEXDIG )
escape           = %x5C ; \

;; NOTE: Multiline strings require additional parser logic
;;  - If the opening """ is followed immediately by a newline, it's discarded
;;  - If the closing """ is on its own line, discard the trailing newline
;;  - Every line should have whitespace trimmed equal to the whitespace left
;;    of the closing """
;; These rules aim to replicate Nix:
;; https://nix.dev/manual/nix/2.24/language/syntax#string-literal
multiline-string = triple-quote *ml-char triple-quote

ml-char          = unescaped-ml / escape-seq / nl
unescaped-ml     = %x20-5B / %x5D-10FFFF ; excludes \

quoted-string    = quotation-mark *char quotation-mark

char             = unescaped / escape-seq
unescaped        = %x20-21 / %x23-5B / %x5D-10FFFF

;; Numbers
number        = [ minus ] num

minus         = %x2D ; -
num           = (int [ frac ]) / ( PERIOD 1*DIGIT )
int           = 1*DIGIT
frac          = PERIOD 1*DIGIT
zero          = %x30 ; 0

;; Non-Tokens
comment            = "#" *non-ascii-or-space
non-ascii-or-space = %x20-10FFFF
ws                 = *( SPACE / TAB )
nl                 = [ CR ] LF
block-ws           = *( ws / nl / comment-line )

;; Primitives
SPACE  = %x20
TAB    = %x09
CR     = %x0D
LF     = %x0A
PERIOD = %x2E
ALPHA  = %x41-5A / %x61-7A
DIGIT  = %x30-39
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"
